title: SAS
author: CandelaCampbell
email: candelacampbell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Best mechanics by far

# social links
facebook_username: candelacampbell
instagram_username:  candelacampbell

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
